#!/bin/bash

# Railway.app Deployment Script
# FREE tier: $5 credit/month (usually enough)
# https://railway.app

echo "🚀 Railway.app Deployment Helper"
echo "=================================="
echo ""
echo "✨ Railway makes deployment SUPER SIMPLE"
echo ""
echo "Step 1: Go to https://railway.app"
echo "Step 2: Sign up with GitHub"
echo "Step 3: Click 'New Project' > 'Deploy from GitHub'"
echo "Step 4: Select: touhid365/Fraud_Detection"
echo ""
echo "That's it! Railway will:"
echo "  ✅ Auto-detect services (backend, frontend, ml-model)"
echo "  ✅ Create MongoDB database automatically"
echo "  ✅ Deploy all services at once"
echo "  ✅ Set up environment variables"
echo "  ✅ Generate URLs for each service"
echo ""
echo "Your Services Will Be Available At:"
echo "  Frontend: https://<project>.railway.app"
echo "  Backend: https://<project>-backend.railway.app"
echo "  ML Model: https://<project>-ml.railway.app"
echo "  Database: Managed by Railway"
echo ""
echo "Environment Variables (automatically set):"
echo "  MONGODB_URI: Automatically generated"
echo "  JWT_SECRET: Set in Railway dashboard"
echo "  NODE_ENV: production"
echo ""
echo "Cost: FREE tier + $5/month credit"
echo "  Enough for:"
echo "    - 2 web services"
echo "    - 1 database"
echo "    - ~100GB data transfer"
echo ""
echo "📚 Railway Documentation:"
echo "   https://docs.railway.app"
echo ""
echo "🎉 Go to https://railway.app and start deploying!"
