#!/bin/bash

# Dokku Deployment (Heroku Alternative)
# Deploy on $5/month DigitalOcean VPS
# Total cost: $5/month for hosting
# https://dokku.com

echo "🚀 Dokku Deployment (Heroku Alternative)"
echo "========================================="
echo ""
echo "This is the cheapest PRODUCTION option: $5/month"
echo ""
echo "Step 1: Create DigitalOcean Droplet (https://www.digitalocean.com)"
echo "  1. Sign up at digitalocean.com"
echo "  2. Create new Droplet"
echo "  3. Choose 'Dokku' from 'Select Image'"
echo "  4. Choose Basic plan: $5/month"
echo "  5. Create droplet"
echo ""
echo "Step 2: SSH into your droplet"
echo "  ssh root@your-droplet-ip"
echo ""
echo "Step 3: Install Dokku (if not pre-installed)"
echo "  wget https://raw.githubusercontent.com/dokku/dokku/master/bootstrap.sh"
echo "  sudo bash bootstrap.sh"
echo ""
echo "Step 4: Create app"
echo "  dokku apps:create fraud-detection"
echo ""
echo "Step 5: Create database"
echo "  dokku plugin:install https://github.com/dokku/dokku-mongo.git"
echo "  dokku mongo:create fraud-detection-db"
echo "  dokku mongo:link fraud-detection-db fraud-detection"
echo ""
echo "Step 6: Set environment variables"
echo "  dokku config:set fraud-detection JWT_SECRET=your-secret"
echo "  dokku config:set fraud-detection NODE_ENV=production"
echo ""
echo "Step 7: Add git remote (on your local machine)"
echo "  git remote add dokku dokku@your-droplet-ip:fraud-detection"
echo ""
echo "Step 8: Deploy with git push"
echo "  git push dokku main"
echo ""
echo "That's it! Your app is live!"
echo ""
echo "Your app will be at:"
echo "  https://fraud-detection.your-droplet-ip.nip.io"
echo ""
echo "Advantages:"
echo "  ✅ $5/month (cheapest production)"
echo "  ✅ Like Heroku but on your own server"
echo "  ✅ Full control"
echo "  ✅ Auto SSL with Let's Encrypt"
echo "  ✅ Easy deployments with git push"
echo ""
echo "📚 Dokku Docs: https://dokku.com"
echo "📚 DigitalOcean: https://www.digitalocean.com"
echo ""
echo "🎉 Total cost: $5/month for hosting + domain name"
